---
resources:
- name: trail
  type: git
  source:
    uri: ((repo_url))
    branch: ((branch))
    private_key: ((repo_key))

jobs:
- name: unit
  plan:
  - get: trail
    trigger: true
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alikov/clojure-dev
          tag: latest
      inputs:
        - name: trail
      run:
        path: echo
        args: ["Run unit tests here"]

- name: integration
  plan:
  - get: trail
    passed:
      - unit
    trigger: true
  - task: build-trail
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alikov/clojure-dev
          tag: latest
      inputs:
        - name: trail
      outputs:
        - name: build
      run:
        path: sh
        args:
          - "-c"
          - "cd trail; make uberjar; cp -r target ../build/; cp Dockerfile ../build/; cp Makefile ../build/; git rev-parse HEAD >../build/tag"

  - task: push-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alikov/docker-client
          tag: latest
      inputs:
        - name: build
      run:
        path: sh
        args:
          - "-c"
          - "cd build; make DOCKER_REPOSITORY=${DOCKER_APP_REPO} DOCKER_TAG=$(cat tag) push-image"
    params:
      DOCKER_HOST: ((docker_host))
      DOCKER_APP_REPO: ((docker_app_repo))

  - task: kubernetes-up
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alikov/kubectl
          tag: latest
      inputs:
        - name: trail
        - name: build
      outputs:
        - name: kubernetes
      run:
        path: sh
        args:
          - "-c"
          - "cd trail; make DOCKER_REPOSITORY=${DOCKER_APP_REPO} DOCKER_TAG=$(cat ../build/tag) STATE_FILE=../kubernetes/stack.namespace ADDRESS_FILE=../kubernetes/app.address kubernetes-up"
    params:
      KUBECTL_CMD: "./kubernetes/kubectl-wrapper.sh"
      DOCKER_APP_REPO: ((docker_app_repo))
      KUBERNETES_API_URL: ((kubernetes_api_url))
      KUBERNETES_API_USER: ((kubernetes_api_user))
      KUBERNETES_API_PASSWORD: ((kubernetes_api_password))

  - task: integrations-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alikov/trail-behave
          tag: latest
      inputs:
        - name: trail
        - name: kubernetes
      run:
        path: sh
        args:
            - "-c"
            - "cd trail; make ADDRESS_FILE=../kubernetes/app.address integration-test"
    ensure:
      task: kubernetes-down
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alikov/kubectl
            tag: latest
        inputs:
          - name: trail
          - name: build
          - name: kubernetes
        run:
          path: sh
          args:
            - "-c"
            - "cd trail; make DOCKER_REPOSITORY=${DOCKER_APP_REPO} DOCKER_TAG=$(cat ../build/tag) STATE_FILE=../kubernetes/stack.namespace ADDRESS_FILE=../kubernetes/app.address kubernetes-down"
      params:
        KUBECTL_CMD: "./kubernetes/kubectl-wrapper.sh"
        DOCKER_APP_REPO: ((docker_app_repo))
        KUBERNETES_API_URL: ((kubernetes_api_url))
        KUBERNETES_API_USER: ((kubernetes_api_user))
        KUBERNETES_API_PASSWORD: ((kubernetes_api_password))
