---

apiVersion: v1
kind: Pod
metadata:
  name: trail
  labels:
    app: trail
spec:
  restartPolicy: OnFailure
  containers:
  - name: trail
    image: "${APP_IMAGE}"
    env:
    - name: DATABASE_URL
      value: "postgresql://trail@localhost/trail"
    - name: PORT
      value: "8080"
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "java -jar /app/server.jar migrate && java -jar /app/server.jar start"
  - name: postgres
    image: "${POSTGRES_IMAGE}"
    env:
      - name: POSTGRES_USER
        value: trail
